// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGY8fw80U6rRE5oOEFWIm1tlM9hb-dShE',
    appId: '1:167805906999:android:63a13139559a195e6a8fb2',
    messagingSenderId: '167805906999',
    projectId: 'mychatapp-c4043',
    storageBucket: 'mychatapp-c4043.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtq56snwEUpNgQ8JhxyEHYPMFISwlSxZs',
    appId: '1:167805906999:ios:b02dbf36fc3cfe696a8fb2',
    messagingSenderId: '167805906999',
    projectId: 'mychatapp-c4043',
    storageBucket: 'mychatapp-c4043.firebasestorage.app',
    iosBundleId: 'com.example.nineHourChatApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIjJ9RDUITyjjR_8Gj8uwKAVqjMBiyxlU',
    appId: '1:167805906999:web:67c2b5d7bfaf01406a8fb2',
    messagingSenderId: '167805906999',
    projectId: 'mychatapp-c4043',
    authDomain: 'mychatapp-c4043.firebaseapp.com',
    storageBucket: 'mychatapp-c4043.firebasestorage.app',
    measurementId: 'G-BQ9D16F07G',
  );
}
